### ISSUE TITLE
Morpheus parity

### ISSUE THREAD

**Issue by gabro** [buildo/metarpheus#16]
Just as a recap, this are the issues currently marked as "morpheus-parity"

- [x] #7 Support overrides for hard-to-parse routes
- [x] #8 Output models in topological order for easier generation of client code
- [x] #11 Extract `case enum`s
- [x] #12 Parse aliases for segment matchers for spray `path` directive 

@utaal can you check whether I forgot something and/or whether all of these are up-to-date and really blocking.
I'd like to start writing a IR -> JS interpreter soon and switch to metarpheus :shipit:

**Comment by gabro** [comment]
Next week we'll port of escalapio from morpheus to metarpheus. Once metarpheus can parse it correctly, I will close this issue.

Wait for it...

**Comment by gabro** [comment]
👍 🎉
